/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.novoda.meuh;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int stat_sample=0x7f020000;
    }
    public static final class id {
        public static final int txt_X=0x7f050004;
        public static final int txt_Y=0x7f050005;
        public static final int txt_accuracy=0x7f050003;
        public static final int txt_accuracy_lbl=0x7f050002;
        public static final int txt_status=0x7f050001;
        public static final int txt_status_lbl=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int moo_serv_lbl=0x7f040009;
        public static final int moo_serv_start=0x7f040007;
        public static final int moo_serv_stop=0x7f040008;
        public static final int str_X=0x7f040005;
        public static final int str_Y=0x7f040006;
        public static final int str_accuracy=0x7f040004;
        public static final int str_accuracy_lbl=0x7f040003;
        public static final int str_status=0x7f040002;
        public static final int str_status_lbl=0x7f040001;
    }
}
